service:
    name: hello-world
    config:
      accountId: CLOUDFLARE_ACCOUNT_ID
      zoneId: CLOUDFLARE_ZONE_ID
      workers:
        hello:
          routes:
            - example.com/hello/*
        foo_script:
          routes:
            - example.com/foo/*

provider:
  name: cloudflare

plugins:
  - serverless-cloudflare-workers

functions:
  proxy:
    worker: proxy
    script: dist/worker
    events:
      - http:
          url: example.com/hello/user
          method: GET
          headers:
            someKey: someValue
